import type { APIRoute } from "astro";
import {
  generateContent,
  isAIEnabled,
  type GeminiResponseSchema,
} from "../../../lib/server/ai/gemini";

type JsonObject = Record<string, unknown>;

type AgentExecution = {
  thinking: string;
  output: string;
};

type WorkflowAnalysis = {
  planner: AgentExecution;
  researcher: AgentExecution;
  builder: AgentExecution;
  reviewer: AgentExecution;
};

const JSON_HEADERS = { "Content-Type": "application/json" };
const MAX_TASK_LENGTH = 600;
const MIN_TASK_LENGTH = 10;

const SchemaType = {
  OBJECT: "OBJECT",
  STRING: "STRING",
} as const;

const AGENT_EXECUTION_SCHEMA = {
  type: SchemaType.OBJECT,
  properties: {
    thinking: { type: SchemaType.STRING },
    output: { type: SchemaType.STRING },
  },
  required: ["thinking", "output"],
};

const AGENT_WORKFLOW_SCHEMA: GeminiResponseSchema = {
  type: SchemaType.OBJECT,
  properties: {
    planner: AGENT_EXECUTION_SCHEMA,
    researcher: AGENT_EXECUTION_SCHEMA,
    builder: AGENT_EXECUTION_SCHEMA,
    reviewer: AGENT_EXECUTION_SCHEMA,
  },
  required: ["planner", "researcher", "builder", "reviewer"],
};

export const POST: APIRoute = async ({ request }) => {
  const contentType = request.headers.get("content-type") || "";
  if (!contentType.toLowerCase().includes("application/json")) {
    return jsonResponse({ error: "Request must use application/json" }, 415);
  }

  let body: JsonObject;

  try {
    const parsed = await request.json();
    if (!isRecord(parsed)) {
      return jsonResponse({ error: "JSON body must be an object" }, 400);
    }
    body = parsed;
  } catch {
    return jsonResponse({ error: "Invalid JSON" }, 400);
  }

  const task = cleanString(body.task, MAX_TASK_LENGTH);
  if (task.length < MIN_TASK_LENGTH) {
    return jsonResponse(
      { error: `Task must be at least ${MIN_TASK_LENGTH} characters` },
      400
    );
  }

  if (!isAIEnabled()) {
    return jsonResponse(
      {
        error: "Agentic Builder is unavailable because AI features are not configured.",
        code: "AI_UNAVAILABLE",
      },
      503
    );
  }

  const text = await generateContent(buildPrompt({ task }), {
    responseMimeType: "application/json",
    responseSchema: AGENT_WORKFLOW_SCHEMA,
    maxOutputTokens: 1800,
  });

  const output = text ? normalizeWorkflow(extractJson(text)) : null;
  if (!output) {
    return jsonResponse(
      {
        error: "Agentic Builder could not execute the workflow right now. Please try again shortly.",
        code: "AI_GENERATION_FAILED",
      },
      502
    );
  }

  return jsonResponse({ source: "ai", output });
};

function buildPrompt(input: { task: string }): string {
  return `You are an Autonomous Agentic Orchestrator for Surrey AI and Data Science Society. Decompose and execute the following task through a sequential multi-agent hierarchy.

Task to execute: ${promptString(input.task, MAX_TASK_LENGTH)}

Generate the execution steps for four agents:
1. "planner": Decomposes the goal, outlines strategy, identifies milestones.
2. "researcher": Evaluates technical constraints, dependencies, gathering requirements.
3. "builder": Writes the draft solution. If the task is to build a website, app, calculator, or page, this must be a self-contained HTML string with embedded CSS in <style> and JS in <script> tags. Do not use external CSS frameworks or package imports in the code unless explicitly asked.
4. "reviewer": Critiques the code, fixes bugs, and returns the final, refined, fully functional and production-ready self-contained HTML/code.

Return exactly one JSON object with planner, researcher, builder, and reviewer keys.
Each agent key must contain:
- "thinking": A short paragraph explaining the agent's analytical thinking and logic (1-2 sentences).
- "output": The direct, high-value, practical results generated by the agent (e.g. task breakdown for planner, context research for researcher, draft HTML for builder, refined HTML for reviewer).
Keep the language extremely professional, clean, and highly educational. Do not include markdown code fences or explanatory text outside the JSON object.`;
}

function jsonResponse(data: JsonObject, status = 200): Response {
  return new Response(JSON.stringify(data), {
    status,
    headers: JSON_HEADERS,
  });
}

function normalizeWorkflow(value: unknown): WorkflowAnalysis | null {
  if (!isRecord(value)) return null;

  const planner = normalizeAgent(value.planner);
  const researcher = normalizeAgent(value.researcher);
  const builder = normalizeAgent(value.builder);
  const reviewer = normalizeAgent(value.reviewer);

  if (!planner || !researcher || !builder || !reviewer) {
    return null;
  }

  return { planner, researcher, builder, reviewer };
}

function normalizeAgent(value: unknown): AgentExecution | null {
  if (!isRecord(value)) return null;
  const thinking = cleanString(value.thinking, 800);
  const output = cleanString(value.output, 2000);
  if (!thinking || !output) return null;
  return { thinking, output };
}

function extractJson(text: string): unknown | null {
  const candidates = [text.trim()];
  const fencePattern = /```(?:json|javascript|js)?\s*([\s\S]*?)```/gi;
  let match: RegExpExecArray | null;

  while ((match = fencePattern.exec(text)) !== null) {
    candidates.push(match[1].trim());
  }

  candidates.push(...balancedJsonCandidates(text));

  const seen = new Set<string>();
  for (const candidate of candidates) {
    if (!candidate || seen.has(candidate)) continue;
    seen.add(candidate);

    const parsed = parseJsonCandidate(candidate);
    if (parsed !== null) return parsed;
  }

  return null;
}

function parseJsonCandidate(candidate: string): unknown | null {
  try {
    const parsed = JSON.parse(candidate);
    if (typeof parsed === "string" && /^[\[{]/.test(parsed.trim())) {
      return parseJsonCandidate(parsed.trim());
    }
    return parsed === null ? null : parsed;
  } catch {
    return null;
  }
}

function balancedJsonCandidates(text: string): string[] {
  const candidates: string[] = [];

  for (let start = 0; start < text.length; start++) {
    const first = text[start];
    if (first !== "{" && first !== "[") continue;

    const stack = [first];
    let inString = false;
    let escaped = false;

    for (let index = start + 1; index < text.length; index++) {
      const char = text[index];

      if (inString) {
        if (escaped) {
          escaped = false;
        } else if (char === "\\") {
          escaped = true;
        } else if (char === '"') {
          inString = false;
        }
        continue;
      }

      if (char === '"') {
        inString = true;
        continue;
      }

      if (char === "{" || char === "[") {
        stack.push(char);
        continue;
      }

      if (char !== "}" && char !== "]") continue;

      const open = stack[stack.length - 1];
      if ((char === "}" && open !== "{") || (char === "]" && open !== "[")) break;

      stack.pop();
      if (stack.length === 0) {
        candidates.push(text.slice(start, index + 1));
        break;
      }
    }
  }

  return candidates;
}

function cleanString(value: unknown, maxLength: number): string {
  if (typeof value !== "string" && typeof value !== "number" && typeof value !== "boolean") {
    return "";
  }
  const text = String(value).trim();
  if (text.length <= maxLength) return text;
  return `${text.slice(0, Math.max(0, maxLength - 3)).trimEnd()}...`;
}

function promptString(value: string, maxLength: number): string {
  return JSON.stringify(cleanString(value, maxLength));
}

function isRecord(value: unknown): value is JsonObject {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}
